config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_service.urls', namespace='mail_service')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_service/urls.py
from django.urls import path

from mail_service.apps import MailServiceConfig
from mail_service.services import MailingService
from mail_service.views import ClientListView, ClientDetailView, home_view, ClientUpdateView, ClientCreateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageUpdateView, MessageCreateView, MessageDeleteView, \
    MailingListView, MailingDetailView, MailingUpdateView, MailingCreateView, MailingDeleteView, StatisticsView

app_name = MailServiceConfig.name


urlpatterns = [
    path('', home_view, name='home'),
    path('statistics/', StatisticsView.as_view(), name='statistics'),
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('message/list/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing/list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path("mailing/<int:pk>/send/", MailingService.send_mailing, name="send_mailing"),
    path("mailing/<int:pk>/finish/", MailingUpdateView.finish_mailing, name="finish_mailing"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView, profile_view, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('profile/', profile_view, name="profile"),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('user/list/', UserListView.as_view(), name='user_list'),
    path("user/<int:pk>/block/", UserUpdateView.block_user, name="block_user"),
]

mail_service/forms.py
from django import forms
from django.forms import BooleanField, DateTimeInput

from mail_service.models import Client, Message, Mailing


class StyleFormMixin:
    """
    Миксин для настройки стилей форм.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания клиента.
    """

    class Meta:
        model = Client
        fields = ('email', 'name', 'comment')

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({
            'placeholder': 'Введите email получателя'
        })

        self.fields['name'].widget.attrs.update({
            'placeholder': 'Введите имя получателя'
        })

        self.fields['comment'].widget.attrs.update({
            'placeholder': 'Введите комментарий'
        })


class MessageForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания сообщения.
    """

    class Meta:
        model = Message
        fields = ('subject', 'message')

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        self.fields['subject'].widget.attrs.update({
            'placeholder': 'Введите тему письма'
        })

        self.fields['message'].widget.attrs.update({
            'placeholder': 'Введите сообщение'
        })


class MailingForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания рассылки.
    """

    class Meta:
        model = Mailing
        fields = ('message', 'clients', 'status', 'start_sending_at', 'end_sending_at')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields["end_sending_at"].widget = forms.DateTimeInput(
            attrs={"type": "datetime-local", 'class': 'form-control'})
        self.fields["start_sending_at"].widget = forms.DateTimeInput(
            attrs={"type": "datetime-local", 'class': 'form-control'})

        if user:
            self.fields['message'].queryset = Message.objects.filter(owner=user)
            self.fields['clients'].queryset = Client.objects.filter(owner=user)

mail_service/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from mail_service.forms import ClientForm, MessageForm, MailingForm
from mail_service.models import Client, Mailing, Message, Attempt
from mail_service.services import MailingService


def home_view(request):
    """
    Контроллер для главной страницы.
    """
    mailing_count = Mailing.objects.count()
    started_mailing_count = Mailing.objects.filter(status='started').count()
    clients = Client.objects.count()
    context = {
        'mailing_count': mailing_count,
        'started_mailing_count': started_mailing_count,
        'clients': clients,
    }
    return render(request, 'mail_service/home.html', context)


class StatisticsView(LoginRequiredMixin, TemplateView):
    """
    Класс для отображения статистики по рассылкам.
    """

    template_name = "mail_service/statistics.html"

    def get_context_data(self, **kwargs):
        """
        Добавление параметров в контекст.
        """

        context = super().get_context_data(**kwargs)
        user = self.request.user
        mailings = Mailing.objects.filter(owner=user)
        attempts = Attempt.objects.filter(mailing__in=mailings)
        print(attempts)

        success = 0
        failure = 0
        mail_count = 0

        for attempt in attempts:
            if attempt.status == "success":
                success += 1
                mail_count += attempt.mailing.clients.count()

            else:
                failure += 1
        context['mail_count'] = mail_count
        context['success'] = success
        context['failure'] = failure
        context['attempts'] = attempts

        return context


class ClientListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения списка получателей рассылки.
    """
    model = Client

    # paginate_by = 5

    def get_queryset(self):
        """
        Переопределение queryset.
        """
        if not self.request.user.has_perm('can_view_client_list'):
            return MailingService.caching(super().get_queryset(), self.model, self.request.user)
        else:
            return MailingService.caching(super().get_queryset(), self.model)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для отображения данных о получателе рассылки.
    """
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания получателя рассылки.
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mail_service:home')

    def form_valid(self, form):
        client = form.save(commit=False)
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для редактирования данных получателя рассылки.
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ClientForm
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления получателя рассылки.
    """
    model = Client
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return self.form_class
        raise PermissionDenied

    def form_valid(self, form):
        user = self.request.user
        if user == self.object.owner:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения списка писем.
    """
    model = Message

    # paginate_by = 5

    def get_queryset(self):
        if not self.request.user.has_perm('can_view_message_list'):
            return MailingService.caching(super().get_queryset(), self.model, self.request.user)
        else:
            return MailingService.caching(super().get_queryset(), self.model)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления письма.
    """
    model = Message
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return self.form_class
        raise PermissionDenied

    def form_valid(self, form):
        user = self.request.user
        if user == self.object.owner:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        raise PermissionDenied


class MessageDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для отображения данных письма.
    """
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания письма.
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mail_service:home')

    def form_valid(self, form):
        message = form.save(commit=False)
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для редактирования письма.
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MessageForm
        raise PermissionDenied


class MailingListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения списка рассылок.
    """
    model = Mailing

    # paginate_by = 5

    def get_queryset(self):
        if not self.request.user.has_perm('mail_service.can_finish_mailing'):
            return MailingService.caching(super().get_queryset(), self.model, self.request.user)
        else:
            return MailingService.caching(super().get_queryset(), self.model)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления рассылки.
    """
    model = Mailing
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return self.form_class
        raise PermissionDenied

    def form_valid(self, form):
        user = self.request.user
        if user == self.object.owner:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        raise PermissionDenied


class MailingDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра рассылки.
    """
    model = Mailing


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания рассылки.
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mail_service:home')

    def form_valid(self, form):
        mailing = form.save(commit=False)
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super().get_form_kwargs(*args, **kwargs)
        form_kwargs['user'] = self.request.user
        print(form_kwargs['user'])
        return form_kwargs


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер редактирования рассылки.
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MailingForm
        raise PermissionDenied

    @staticmethod
    def finish_mailing(request, pk):
        finish_mailing = Mailing.objects.get(pk=pk)

        if not request.user.has_perm('mail_service.can_finish_mailing'):
            return HttpResponseForbidden("У вас нет прав для отключения рассылки.")
        else:
            finish_mailing.status = 'completed'
            finish_mailing.save()
        return redirect(reverse("mail_service:mailing_list"))

mail_service/templates/mail_service/includes/footer.html
<!-- footer.html -->
<div class="pt-5 my-md-1 pt-md-5">
    <div class="row">
        <div class="col-12 col-md">
            MailService
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
            {% if user.is_authenticated %}
            <small class="d-block mb-3 text-muted">Вы вошли как {{ user.email }}</small>
            {% endif %}
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</div>

mail_service/templates/mail_service/includes/nav_menu.html
<!-- header.html -->
<nav class="navbar navbar-dark bg-dark" aria-label="First navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'mail_service:home'%}">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-envelope-at"
                 viewBox="0 0 16 16">
                <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2zm3.708 6.208L1 11.105V5.383zM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2z"/>
                <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648m-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
            </svg>
            MailService</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01"
                aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample01">
            <ul class="navbar-nav me-auto mb-2">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'users:profile' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                             class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                            <path fill-rule="evenodd"
                                  d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                        </svg>
                        <span class="h6">Просмотр профиля</span>
                    </a>
                    <a class="nav-link" href="{% url 'users:update' user.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                             class="bi bi-gear" viewBox="0 0 16 16">
                            <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492M5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0"/>
                            <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115z"/>
                        </svg>
                        <span class="h6">Редактировать профиль</span>
                    </a>
                    {% if "users.view_user" in perms%}
                    <a class="nav-link" href="{% url 'users:user_list' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                             class="bi bi-people-fill" viewBox="0 0 16 16">
                            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5"/>
                        </svg>
                        <span class="h6">Список пользователей</span>
                    </a>
                    {% endif %}
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="nav-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                 class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
                                <path fill-rule="evenodd"
                                      d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                            </svg>
                            <span class="h6">Выйти</span>
                        </button>
                    </form>
                <li class="nav-item dropdown h6">
                    <span class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                        <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/>
                    </svg>
                        Выберите действие</span>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'mail_service:message_list' %}">Сообщения</a></li>
                        <li><a class="dropdown-item" href="{% url 'mail_service:client_list' %}">Клиенты</a></li>
                        <li><a class="dropdown-item" href="{% url 'mail_service:mailing_list' %}">Мои рассылки</a></li>
                        <li><a class="dropdown-item" href="{% url 'mail_service:statistics' %}">Статистика</a></li>
                    </ul>
                </li>
                {% else %}
                <a class="nav-link" href="{% url 'users:login' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                         class="bi bi-box-arrow-in-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                              d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0z"/>
                        <path fill-rule="evenodd"
                              d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708z"/>
                    </svg>
                    <span class="h6">Войти</span></a>
                <a class="nav-link" href="{% url 'users:register' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                         class="bi bi-person-add" viewBox="0 0 16 16">
                        <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/>
                        <path d="M8.256 14a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1z"/>
                    </svg>
                    <span class="h6">Регистрация</span></a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>