config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_service.urls', namespace='mail_service')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_service/urls.py
from django.urls import path

from mail_service.apps import MailServiceConfig
from mail_service.services import MailingService
from mail_service.views import ClientListView, ClientDetailView, home_view, ClientUpdateView, ClientCreateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageUpdateView, MessageCreateView, MessageDeleteView, \
    MailingListView, MailingDetailView, MailingUpdateView, MailingCreateView, MailingDeleteView, StatisticsView

app_name = MailServiceConfig.name


urlpatterns = [
    path('', home_view, name='home'),
    path('statistics/', StatisticsView.as_view(), name='statistics'),
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('message/list/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing/list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path("mailing/<int:pk>/send/", MailingService.send_mailing, name="send_mailing"),
    path("mailing/<int:pk>/finish/", MailingUpdateView.finish_mailing, name="finish_mailing"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView, profile_view, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('profile/', profile_view, name="profile"),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('user/list/', UserListView.as_view(), name='user_list'),
    path("user/<int:pk>/block/", UserUpdateView.block_user, name="block_user"),
]

mail_service/forms.py
from django import forms
from django.forms import BooleanField, DateTimeInput

from mail_service.models import Client, Message, Mailing


class StyleFormMixin:
    """
    Миксин для настройки стилей форм.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания клиента.
    """

    class Meta:
        model = Client
        fields = ('email', 'name', 'comment')

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({
            'placeholder': 'Введите email получателя'
        })

        self.fields['name'].widget.attrs.update({
            'placeholder': 'Введите имя получателя'
        })

        self.fields['comment'].widget.attrs.update({
            'placeholder': 'Введите комментарий'
        })


class MessageForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания сообщения.
    """

    class Meta:
        model = Message
        fields = ('subject', 'message')

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        self.fields['subject'].widget.attrs.update({
            'placeholder': 'Введите тему письма'
        })

        self.fields['message'].widget.attrs.update({
            'placeholder': 'Введите сообщение'
        })


class MailingForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для создания рассылки.
    """

    class Meta:
        model = Mailing
        fields = ('message', 'clients', 'status', 'start_sending_at', 'end_sending_at')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields["end_sending_at"].widget = forms.DateTimeInput(
            attrs={"type": "datetime-local", 'class': 'form-control'})
        self.fields["start_sending_at"].widget = forms.DateTimeInput(
            attrs={"type": "datetime-local", 'class': 'form-control'})

        if user:
            self.fields['message'].queryset = Message.objects.filter(owner=user)
            self.fields['clients'].queryset = Client.objects.filter(owner=user)

mail_service/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from mail_service.forms import ClientForm, MessageForm, MailingForm
from mail_service.models import Client, Mailing, Message, Attempt
from mail_service.services import MailingService


def home_view(request):
    """
    Контроллер для главной страницы.
    """
    mailing_count = Mailing.objects.count()
    started_mailing_count = Mailing.objects.filter(status='started').count()
    clients = Client.objects.count()
    context = {
        'mailing_count': mailing_count,
        'started_mailing_count': started_mailing_count,
        'clients': clients,
    }
    return render(request, 'mail_service/home.html', context)


class StatisticsView(LoginRequiredMixin, TemplateView):
    """
    Класс для отображения статистики по рассылкам.
    """

    template_name = "mail_service/statistics.html"

    def get_context_data(self, **kwargs):
        """
        Добавление параметров в контекст.
        """

        context = super().get_context_data(**kwargs)
        user = self.request.user
        mailings = Mailing.objects.filter(owner=user)
        attempts = Attempt.objects.filter(mailing__in=mailings)
        print(attempts)

        success = 0
        failure = 0
        mail_count = 0

        for attempt in attempts:
            if attempt.status == "success":
                success += 1
                mail_count += attempt.mailing.clients.count()

            else:
                failure += 1
        context['mail_count'] = mail_count
        context['success'] = success
        context['failure'] = failure
        context['attempts'] = attempts

        return context


class ClientListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения списка получателей рассылки.
    """
    model = Client

    # paginate_by = 5

    def get_queryset(self):
        """
        Переопределение queryset.
        """
        if not self.request.user.has_perm('can_view_client_list'):
            return MailingService.caching(super().get_queryset(), self.model, self.request.user)
        else:
            return MailingService.caching(super().get_queryset(), self.model)


class ClientDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для отображения данных о получателе рассылки.
    """
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания получателя рассылки.
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mail_service:home')

    def form_valid(self, form):
        client = form.save(commit=False)
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для редактирования данных получателя рассылки.
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ClientForm
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления получателя рассылки.
    """
    model = Client
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return self.form_class
        raise PermissionDenied

    def form_valid(self, form):
        user = self.request.user
        if user == self.object.owner:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения списка писем.
    """
    model = Message

    # paginate_by = 5

    def get_queryset(self):
        if not self.request.user.has_perm('can_view_message_list'):
            return MailingService.caching(super().get_queryset(), self.model, self.request.user)
        else:
            return MailingService.caching(super().get_queryset(), self.model)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления письма.
    """
    model = Message
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return self.form_class
        raise PermissionDenied

    def form_valid(self, form):
        user = self.request.user
        if user == self.object.owner:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        raise PermissionDenied


class MessageDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для отображения данных письма.
    """
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания письма.
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mail_service:home')

    def form_valid(self, form):
        message = form.save(commit=False)
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для редактирования письма.
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MessageForm
        raise PermissionDenied


class MailingListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения списка рассылок.
    """
    model = Mailing

    # paginate_by = 5

    def get_queryset(self):
        if not self.request.user.has_perm('mail_service.can_finish_mailing'):
            return MailingService.caching(super().get_queryset(), self.model, self.request.user)
        else:
            return MailingService.caching(super().get_queryset(), self.model)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """
    Контроллер для удаления рассылки.
    """
    model = Mailing
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return self.form_class
        raise PermissionDenied

    def form_valid(self, form):
        user = self.request.user
        if user == self.object.owner:
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        raise PermissionDenied


class MailingDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для просмотра рассылки.
    """
    model = Mailing


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Контроллер для создания рассылки.
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mail_service:home')

    def form_valid(self, form):
        mailing = form.save(commit=False)
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super().get_form_kwargs(*args, **kwargs)
        form_kwargs['user'] = self.request.user
        print(form_kwargs['user'])
        return form_kwargs


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер редактирования рассылки.
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mail_service:home')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MailingForm
        raise PermissionDenied

    @staticmethod
    def finish_mailing(request, pk):
        finish_mailing = Mailing.objects.get(pk=pk)

        if not request.user.has_perm('mail_service.can_finish_mailing'):
            return HttpResponseForbidden("У вас нет прав для отключения рассылки.")
        else:
            finish_mailing.status = 'completed'
            finish_mailing.save()
        return redirect(reverse("mail_service:mailing_list"))

mail_service/templates/mail_service/client_confirm_delete.html
{% extends 'mail_service/base.html' %}
{% block title %} Удаление клиента {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1 class="display-5">Удаление клиента {{ object.email }}</h1>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6">
        <form method="POST" class="post-form row" enctype="multipart/form-data">
            <div class="card p-3">
                <p class="card-text h3">Вы подтверждаете удаление клиента {{object.email}}?</p>
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a href="{% url 'mail_service:client_list' %}" class="btn btn-secondary mt-3">Отмена</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/client_detail.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Информация о клиенте {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h1 class="display-5">Информация о клиенте</h1>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h2 class="card-title pricing-card-title">{{ object.email }}</h2>
            </div>
            <div class="card-body">
                <h4>{{ object.name }}</h4>
                <h6>{{ object.comment }}</h6>
                {% if user == object.owner %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:client_update' object.pk %}">Редактировать</a>
                {% endif %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:home'%}">На Главную</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/client_form.html
{% extends 'mail_service/base.html' %}
{% block title %} Добавление нового клиента {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h1 class="display-5">{% if object %}
        Редактирование клиента
        {% else %}
        Добавление клиента
        {% endif %}</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-6">
    <form method="POST" class="post-form row" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label>Email</label>
            {{ form.email }}
            {% if form.email.errors %}
            <small class="text-danger">{{ form.email.errors.0 }}</small>
            {% endif %}
        </div>
        <div class="mb-3">
            <label>Имя</label>
            {{ form.name }}
            {% if form.name.errors %}
            <small class="text-danger">{{ form.name.errors.0 }}</small>
            {% endif %}
        </div>
        <div class="mb-3">
            <label>Комментарий</label>
            {{ form.comment }}
            {% if form.comment.errors %}
            <small class="text-danger">{{ form.comment.errors.0 }}</small>
            {% endif %}
        </div>
        <button type="submit" class="mb-3 save btn btn-outline-primary">
            {% if object %}
            Сохранить изменения
            {% else %}
            Добавить клиента
            {% endif %}
        </button>
        {% if object %}
        <a type="button" class="btn btn-outline-danger" href="{% url 'mail_service:client_delete' object.pk %}">Удалить клиента</a>
        {% endif %}
    </form>
</div>
{% endblock %}

mail_service/templates/mail_service/client_list.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Получатели рассылок {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h3>Ваши получатели рассылок</h3>
</div>
{% endblock %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <div class="row text-center">
        <ul class="list-group">
            {% for client in object_list %}
            <li class="list-group-item"><h4 class="my-0 font-weight-normal">{{ client.email }}</h4>
                <p>{{ client.name }}</p>
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:client_detail' client.pk %}">Подробнее...</a></li>
            {% endfor %}
            <li class="list-group-item"><a type="button"
                                           class="btn btn-lg btn-block btn-outline-primary"
                                           href="{% url 'mail_service:client_create' %}">Добавить уникального
                получателя</a></li>

        </ul>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/home.html
{% extends 'mail_service/base.html' %}
{% block title %} Главная {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h2>Приветствуем Вас на главной странице</h2>
    <h3>Здесь мы собрали статистику нашего почтового сервиса</h3>
</div>
{% endblock %}
{% block content %}
<h3>Количество уникальных получателей: {{ clients }}</h3>
<h3>Общее количество рассылок: {{ mailing_count }}</h3>
<h3>Количество запущенных рассылок: {{ started_mailing_count }}</h3>
{% endblock %}

mail_service/templates/mail_service/mailing_confirm_delete.html
{% extends 'mail_service/base.html' %}
{% block title %} Удаление рассылки {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1 class="display-5">Удаление рассылки {{object.message.subject}}</h1>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6">
        <form method="POST" class="post-form row" enctype="multipart/form-data">
            <div class="card p-3">
                <p class="card-text h3">Вы подтверждаете удаление рассылки {{object.message.subject}}?</p>
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a href="{% url 'mail_service:message_list' %}" class="btn btn-secondary mt-3">Отмена</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/mailing_detail.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Сообщение {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h1 class="display-5">Сообщение</h1>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h2 class="card-title pricing-card-title">{{ object.message.subject }}</h2>
            </div>
            <div class="card-body">
                <h4>{{ object.message.message }}</h4>
                <ul class="list-group">
                    {% for client in object.clients.all %}
                    <li>{{ client }};</li>
                    {% endfor %}
                </ul>
                <p>{{ object.status }}</p>
                <p>{% if start_sending_at %} Дата и время начала рассылки: {{ mailing.start_sending_at|date:"d.m.y H:i" }} {% endif %}</p>
                <p>{% if end_sending_at %} Дата и время начала рассылки: {{ mailing.end_sending_at|date:"d.m.y H:i" }} {% endif %}</p>
                {% if user == object.owner and object.status != 'completed' %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:mailing_update' object.pk %}">Редактировать</a>
                {% if object.status != 'completed' %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:send_mailing' mailing.pk %}">Запустить рассылку</a>
                {% endif %}
                {% endif %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:home'%}">На Главную</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/mailing_list.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Рассылки {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h3>Сообщения</h3>
</div>
{% endblock %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <div class="row text-center">
        <ul class="list-group">
            {% for mailing in object_list %}
            <li class="list-group-item"><h4 class="my-0 font-weight-normal">{{ mailing.message.subject }}</h4>
                <p>{{ mailing.message.message|truncatechars:50 }}</p>
                <ul class="list-group">
                    {% for client in mailing.clients.all %}
                    <li>{{ client }};</li>
                    {% endfor %}
                </ul>
                <p>{{ mailing.status }}</p>
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:mailing_detail' mailing.pk %}">Подробнее...</a>
                {% if perms.mail_service.can_finish_mailing %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:finish_mailing' mailing.pk %}">Отключить рассылку</a></li>
            {% endif %}
            </li>
            {% endfor %}
            <li class="list-group-item"><a type="button"
                                           class="btn btn-lg btn-block btn-outline-primary"
                                           href="{% url 'mail_service:mailing_create' %}">Новая рассылка</a></li>

        </ul>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/message_confirm_delete.html
{% extends 'mail_service/base.html' %}
{% block title %} Удаление сообщения {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1 class="display-5">Удаление сообщения {{object.email}}</h1>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6">
        <form method="POST" class="post-form row" enctype="multipart/form-data">
            <div class="card p-3">
                <p class="card-text h3">Вы подтверждаете удаление сообщения {{object.subject}}?</p>
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    Удалить
                </button>
                <a href="{% url 'mail_service:message_list' %}" class="btn btn-secondary mt-3">Отмена</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/message_detail.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Сообщение {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h1 class="display-5">Сообщение</h1>
</div>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h2 class="card-title pricing-card-title">{{ object.subject }}</h2>
            </div>
            <div class="card-body">
                <h4>{{ object.message }}</h4>
                {% if user == object.owner %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:message_update' object.pk %}">Редактировать</a>
                {% endif %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:home'%}">На Главную</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mail_service/templates/mail_service/message_form.html
{% extends 'mail_service/base.html' %}
{% block title %} Создание сообщения {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h1 class="display-5">{% if object %}
        Редактирование сообщения
        {% else %}
        Новое сообщение
        {% endif %}</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-6">
    <form method="POST" class="post-form row" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label>Тема</label>
            {{ form.subject }}
            {% if form.subject.errors %}
            <small class="text-danger">{{ form.subject.errors.0 }}</small>
            {% endif %}
        </div>
        <div class="mb-3">
            <label>Текст</label>
            {{ form.message }}
            {% if form.message.errors %}
            <small class="text-danger">{{ form.message.errors.0 }}</small>
            {% endif %}
        </div>
        <button type="submit" class="mb-3 save btn btn-outline-primary">
            {% if object %}
            Сохранить изменения
            {% else %}
            Создать сообщение
            {% endif %}
        </button>
        {% if object %}
        <a type="button" class="btn btn-outline-danger" href="{% url 'mail_service:message_delete' object.pk %}">Удалить сообщение</a>
        {% endif %}
    </form>
</div>
{% endblock %}

mail_service/templates/mail_service/message_list.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Сообщения {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h3>Сообщения</h3>
</div>
{% endblock %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <div class="row text-center">
        <ul class="list-group">
            {% for message in object_list %}
            <li class="list-group-item"><h4 class="my-0 font-weight-normal">{{ message.subject }}</h4>
                <p>{{ message.message|truncatechars:100 }}</p>
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'mail_service:message_detail' message.pk %}">Подробнее...</a></li>
            {% endfor %}
            <li class="list-group-item"><a type="button"
                                           class="btn btn-lg btn-block btn-outline-primary"
                                           href="{% url 'mail_service:message_create' %}">Новое сообщение</a></li>

        </ul>
    </div>
</div>
{% endblock %}