config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail_service.urls', namespace='mail_service')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_service/urls.py
from django.urls import path

from mail_service.apps import MailServiceConfig
from mail_service.services import MailingService
from mail_service.views import ClientListView, ClientDetailView, home_view, ClientUpdateView, ClientCreateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageUpdateView, MessageCreateView, MessageDeleteView, \
    MailingListView, MailingDetailView, MailingUpdateView, MailingCreateView, MailingDeleteView, StatisticsView

app_name = MailServiceConfig.name


urlpatterns = [
    path('', home_view, name='home'),
    path('statistics/', StatisticsView.as_view(), name='statistics'),
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client/update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('message/list/', MessageListView.as_view(), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing/list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path("mailing/<int:pk>/send/", MailingService.send_mailing, name="send_mailing"),
    path("mailing/<int:pk>/finish/", MailingUpdateView.finish_mailing, name="finish_mailing"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserUpdateView, profile_view, UserListView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('profile/', profile_view, name="profile"),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('user/list/', UserListView.as_view(), name='user_list'),
    path("user/<int:pk>/block/", UserUpdateView.block_user, name="block_user"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Модель пользователя.
    """
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone_number = models.CharField(
        max_length=15,
        verbose_name="Телефон",
        blank=True,
        null=True,
        help_text="Введите номер телефона",
    )
    country = models.CharField(
        max_length=150, verbose_name="Страна", help_text="Введите страну", blank=True, null=True
    )
    avatar = models.ImageField(
        upload_to="users/avatars/",
        verbose_name="Аватар",
        help_text="Загрузите ваш аватар",
        blank=True,
        null=True,
    )

    token = models.CharField(max_length=100, verbose_name='Token', blank=True, null=True, )

    is_blocked = models.BooleanField(default=False, verbose_name="заблокирован")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'
        ordering = ['email']
        permissions = [
            ("can_block_user", "Can block user"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mail_service.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """
    Форма регистрации пользователя.
    """
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserUpdateForm(StyleFormMixin, UserChangeForm):
    """
    Форма редактирования данных пользователя.
    """
    password = None

    class Meta:
        model = User
        fields = ('phone_number', 'avatar', 'country')

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView

from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User

from config.settings import EMAIL_HOST_USER, DEBUG


class UserCreateView(CreateView):
    """
    Контроллер для регистрации пользователя.
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.token = secrets.token_hex(16)
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{user.token}/'
        send_mail(subject='Подтверждение регистрации',
                  message=f'Спасибо за регистрацию на нашем сайте!\nДля завершения регистрации пройдите по ссылке:\n{url}',
                  from_email=EMAIL_HOST_USER,
                  recipient_list=[user.email, ])
        if DEBUG:
            print(url)
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для редактирования данных пользователя.
    """
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy('mail_service:home')

    @staticmethod
    def block_user(request, pk):
        block_user = User.objects.get(pk=pk)

        if not request.user.has_perm('users.can_block_user'):
            return HttpResponseForbidden("У вас нет прав для блокировки пользователя.")
        else:
            block_user.is_blocked = True
            block_user.save()
        return redirect(reverse("users:user_list"))


def profile_view(request):
    """
    Контроллер для просмотра данных пользователя.
    """
    user = request.user
    context = {'user': user, }
    return render(request, context=context, template_name='users/profile.html')


def email_verification(request, token):
    """
    Верификация пользователя.
    """
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    Класс для отображения списка пользователей.
    """
    model = User
    permission_required = "users.view_user"
    context_object_name = "users"

users/templates/users/login.html
{% extends 'mail_service/base.html' %}
{% block title %} Авторизация {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1 class="display-5">Авторизация</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-6">
    <form method="POST" class="post-form row" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="save btn btn-outline-primary">
            Войти
        </button>
        <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mail_service/base.html' %}
{% block title %} Пароль изменен {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1>Пароль изменен</h1>
</div>
{% endblock %}

{% block content %}
<div class="row">
    <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login' %}">входа в систему</a></p>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Новый пароль {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1>Новый пароль</h1>
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-6">
        <form method="POST" class="post-form row">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label}}">{{f.label}}</label>{{f}}</p>
            <div class="form-error">{{f.errors}}</div>
            {% endfor %}
            <p><button type="submit" class="save btn btn-outline-primary">Сохранить</button></p>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mail_service/base.html' %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Сброс пароля {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1>Восстановление пароля</h1>
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-6">
        <form method="POST" class="post-form row">
            {% csrf_token %}
            {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label}}">{{f.label}}</label>{{f}}</p>
            <div class="form-error">{{f.errors}}</div>
            {% endfor %}
            <p><button type="submit" class="save btn btn-outline-primary">Сбросить пароль</button></p>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'mail_service/base.html' %}
{% block title %} Просмотр профиля {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    <h1 class="display-5">Просмотр профиля</h1>
</div>
{% endblock %}

{% block content %}

<div class="col-6">
    <div class="card" style="width: 18rem;">
        {% if user.avatar %}
        <img src="{{ user.avatar }}" class="img-fluid mb-3">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ user.email }}</h5>
            <p class="card-text">Номер телефона: {{ user.phone_number }}</p>
            <p class="card-text">Страна: {{user.country}}</p>
            <a type="button" class="mb-3 btn btn-lg btn-block btn-outline-primary"
               href="{% url 'users:update' user.pk %}">Редактировать</a>
            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
               href="{% url 'mail_service:home'%}">На Главную</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Регистрация {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-start">
    {% if user.is_authenticated %}
    <h1 class="display-5">Редактирование профиля</h1>
    {% else %}
    <h1 class="display-5">Регистрация</h1>
    {% endif %}
</div>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-6">
        <form method="POST" class="post-form row" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="save btn btn-outline-primary">
                {% if user.is_authenticated %}
                Сохранить изменения
                {% else %}
                Зарегистрироваться
                {% endif %}
            </button>
        </form>
    </div>
    {% if user.is_authenticated %}
    <div class="col-6">
        <div class="card" style="width: 18rem;">
            {% if user.avatar %}
            <img src="{{ user.avatar | media_filter }}" class="img-fluid mb-3">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ user.email }}</h5>
                <p class="card-text">Номер телефона: {{ user.phone_number }}</p>
                <p class="card-text">Страна: {{user.country}}</p>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mail_service/base.html' %}
{% load my_tags %}
{% block title %} Пользователи {% endblock %}
{% block title1 %}
<div class="pricing-header px-2 pb-md-4 text-center">
    <h3>Пользователи:</h3>
</div>
{% endblock %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <div class="row text-center">
        <ul class="list-group">
            {% for user in object_list %}
            <li class="list-group-item"><h4 class="my-0 font-weight-normal">Имя пользователя: {{user.email}}</h4>
                <p>Телефон: {{user.phone_number}}</p>
                <p>Страна: {{user.country}}</p>
                <p>Заблокирован: {{user.is_blocked}}</p>
                {% if perms.users.can_block_user %}
                <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'users:block_user' user.pk %}">Заблокировать</a></li>
            {% endif %}
            {% endfor %}

        </ul>
    </div>
</div>
{% endblock %}